# Generated by Django 5.2.4 on 2025-07-05 10:15

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("groups", models.ManyToManyField(blank=True, to="auth.group")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["name"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("site")),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="plants/"),
                ),
                (
                    "recommended_watering_interval",
                    models.IntegerField(
                        help_text="Recommended watering interval in days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived",
                    models.BooleanField(
                        default=False, help_text="Indicates if the plant is archived"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WateringLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("watered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="watering_logs/"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.plant"
                    ),
                ),
                (
                    "watered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watering_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Watering Log",
                "verbose_name_plural": "Watering Logs",
                "ordering": ["-watered_at"],
                "indexes": [
                    models.Index(
                        fields=["plant", "watered_at"],
                        name="project_wat_plant_i_140b40_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WateringNotification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("notification_time", models.DateTimeField()),
                ("message", models.TextField()),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.plant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Watering Notification",
                "verbose_name_plural": "Watering Notifications",
                "ordering": ["-notification_time"],
                "indexes": [
                    models.Index(
                        fields=["plant", "notification_time"],
                        name="project_wat_plant_i_96eccb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WateringNotificationSubscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.plant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Watering Notification Subscription",
                "verbose_name_plural": "Watering Notification Subscriptions",
                "ordering": ["-subscribed_at"],
                "unique_together": {("user", "plant")},
            },
        ),
    ]
