# Generated by Django 5.2.4 on 2025-07-04 23:36

import django.contrib.sites.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("on_site", django.contrib.sites.managers.CurrentSiteManager("site")),
            ],
        ),
    ]
